#!/usr/bin/env node
/**
 * Builds a standalone, dependency-free HTML file for embedding on
 * afreetools.com/finance/paycheck-calculator.
 *
 * Inlines: tax data, calculation engine, and UI into one file.
 * No runtime fetch, no framework, no external requests.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DIST = join(ROOT, "dist");
mkdirSync(DIST, { recursive: true });

const read = (p) => readFileSync(join(ROOT, p), "utf8");

// Strip ESM export/import keywords for inlining into one scope.
const strip = (src) =>
  src
    .replace(/^import[^;]+;\s*$/gm, "")
    .replace(/^export\s+/gm, "")
    .trim();

// Collect all tax data.
const federal = {};
for (const y of [2025, 2026]) {
  federal[y] = JSON.parse(read(`src/data/federal/us-fed-${y}.json`));
}
const states = {};
const stateDir = join(ROOT, "src", "data", "states");
for (const f of readdirSync(stateDir)) {
  if (!f.endsWith(".json") || f === "index.json") continue;
  const rec = JSON.parse(readFileSync(join(stateDir, f), "utf8"));
  states[`${rec.jurisdiction}-${rec.tax_year}`] = rec;
}
const stateIndex = JSON.parse(read("src/data/states/index.json"));

const engineSrc = strip(read("src/engine/calculator.js"));
const uiSrc = strip(read("src/ui/calculator-ui.js"));
const css = read("src/ui/calculator.css");

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Paycheck Calculator — Take-Home Pay After Taxes</title>
<meta name="description" content="Free US paycheck calculator. Estimate your take-home pay after federal tax, FICA, and state income tax. No signup required." />
<style>
${css}
</style>
</head>
<body>
<main id="paycheck-calculator" class="pc-app" aria-label="Paycheck calculator"></main>

<script type="module">
/* Auto-generated by tools/build.mjs — do not edit directly. */
const FEDERAL = ${JSON.stringify(federal)};
const STATES = ${JSON.stringify(states)};
const STATE_INDEX = ${JSON.stringify(stateIndex)};

${engineSrc}

const getFederal = (y) => FEDERAL[y];
const getState = (code, y) => STATES[\`\${code}-\${y}\`];
const getStateList = () => STATE_INDEX.states;

${uiSrc}

mount(document.getElementById("paycheck-calculator"), {
  calculate, getFederal, getState, getStateList,
});
</script>
</body>
</html>
`;

writeFileSync(join(DIST, "paycheck-calculator.html"), html);
const kb = (Buffer.byteLength(html) / 1024).toFixed(1);
console.log(`Built dist/paycheck-calculator.html (${kb} KB, self-contained)`);
