#!/usr/bin/env node
/**
 * Builds deployment artifacts.
 *
 *  dist/paycheck-engine.js          External ES module for WordPress (cacheable)
 *  dist/paycheck-calculator.html    Standalone self-contained page
 *  dist/wp/*.html                   Copy-paste snippets for the WP editor
 *  dist/wp/3a-schema-webapplication.jsonld  Structured data, one type per file
 *  dist/wp/3b-schema-faq.jsonld             (Rank Math free allows only one)
 *
 * The engine is emitted as an external file rather than inlined into a
 * WordPress page because wpautop mangles inline <script type="module"> blocks.
 * See docs/WORDPRESS-INTEGRATION.md.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DIST = join(ROOT, "dist");
const WPDIR = join(DIST, "wp");
mkdirSync(WPDIR, { recursive: true });

// Remove artifacts from earlier builds so a renamed file cannot linger and be
// deployed by mistake. Only files this build owns are listed.
for (const stale of ["3-schema.jsonld"]) {
  rmSync(join(WPDIR, stale), { force: true });
}

const read = (p) => readFileSync(join(ROOT, p), "utf8");

/**
 * Strips ESM syntax for single-file inlining.
 *
 * Fails loudly on local imports rather than deleting them. Silently removing
 * an import produces a bundle that throws at runtime in the browser, which is
 * far harder to diagnose than a build error.
 */
function stripModuleSyntax(src, label) {
  return src
    .replace(
      /^\s*import\s+(?:[^;'"]+?\s+from\s+)?["']([^"']+)["'];?\s*$/gm,
      (_m, spec) => {
        if (spec.startsWith(".") || spec.startsWith("/")) {
          throw new Error(
            `${label}: unresolved local import "${spec}". ` +
              `The bundler inlines only self-contained files. Either merge ${spec} ` +
              `into ${label}, or add it to the concatenation order in tools/build.mjs.`
          );
        }
        return ""; // bare external import (unused at build time)
      }
    )
    .replace(/^\s*export\s+/gm, "")
    .trim();
}

// ---- tax data ----
const federal = {};
for (const y of [2025, 2026]) federal[y] = JSON.parse(read(`src/data/federal/us-fed-${y}.json`));

const states = {};
const stateDir = join(ROOT, "src", "data", "states");
for (const f of readdirSync(stateDir)) {
  if (!f.endsWith(".json") || f === "index.json") continue;
  const rec = JSON.parse(readFileSync(join(stateDir, f), "utf8"));
  states[`${rec.jurisdiction}-${rec.tax_year}`] = rec;
}
const stateIndex = JSON.parse(read("src/data/states/index.json"));

const engineSrc = stripModuleSyntax(read("src/engine/calculator.js"), "calculator.js");
const uiSrc = stripModuleSyntax(read("src/ui/calculator-ui.js"), "calculator-ui.js");
const css = read("src/ui/calculator.css");

const DATA_BLOCK = `
const FEDERAL = ${JSON.stringify(federal)};
const STATES = ${JSON.stringify(states)};
const STATE_INDEX = ${JSON.stringify(stateIndex)};
const getFederal = (y) => FEDERAL[y];
const getState = (code, y) => STATES[\`\${code}-\${y}\`];
const getStateList = () => STATE_INDEX.states;
`;

const MOUNT_HELPER = `
/**
 * Convenience entry point: wires the engine into the UI.
 * Idempotent, so the inline call and auto-mount cannot double-mount.
 */
function mountCalculator(el) {
  if (!el || el.dataset.pcMounted === "1") return;
  el.dataset.pcMounted = "1";
  return mount(el, { calculate, getFederal, getState, getStateList });
}

/**
 * Auto-mount when a #paycheck-calculator container is present.
 * Lets WordPress load the engine via wp_enqueue_script_module with no inline
 * script at all, which sidesteps wpautop reformatting the JS.
 */
function autoMount() {
  const el = document.getElementById("paycheck-calculator");
  if (el) mountCalculator(el);
}
if (typeof document !== "undefined") {
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", autoMount);
  } else {
    autoMount();
  }
}
`;

const EXPORTS =
  "export { calculate, bracketTax, marginalRate, PERIODS, FILING_STATUSES, " +
  "mount, template, mountCalculator, getFederal, getState, getStateList };";

// ---- 1. external engine module (WordPress) ----
const engineBundle = `/* paycheck-engine.js — generated by tools/build.mjs. Do not edit. */
${DATA_BLOCK}
${engineSrc}
${uiSrc}
${MOUNT_HELPER}
${EXPORTS}
`;
writeFileSync(join(DIST, "paycheck-engine.js"), engineBundle);

// ---- 2. standalone page ----
// The standalone file has no Bootstrap, so this shim covers only the classes the
// calculator markup actually uses. WordPress gets the real Bootstrap 4.6.2 from
// the theme and ignores this entirely.
const BOOTSTRAP_SHIM = `
*, *::before, *::after { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.5; color: #221f28; }
.row { display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; }
.row > [class*="col-"] { position: relative; width: 100%; padding-right: 15px; padding-left: 15px; }
.col-12 { flex: 0 0 100%; max-width: 100%; }
@media (min-width: 768px) {
  .col-md-4 { flex: 0 0 33.333333%; max-width: 33.333333%; }
  .col-md-6 { flex: 0 0 50%; max-width: 50%; }
}
.form-group { margin-bottom: 1rem; }
label { display: inline-block; margin-bottom: .5rem; }
.form-control { display: block; width: 100%; height: calc(1.5em + .75rem + 2px); padding: .375rem .75rem; }
.custom-select { display: block; width: 100%; height: calc(1.5em + .75rem + 2px); padding: .375rem 1.75rem .375rem .75rem; }
.input-group { position: relative; display: flex; flex-wrap: wrap; align-items: stretch; width: 100%; }
.input-group > .form-control { position: relative; flex: 1 1 auto; width: 1%; min-width: 0; margin-bottom: 0; }
.input-group-prepend, .input-group-append { display: flex; }
.input-group-prepend { margin-right: -1px; }
.input-group-append { margin-left: -1px; }
.input-group-text { display: flex; align-items: center; padding: .375rem .75rem; margin-bottom: 0; white-space: nowrap; }
.input-group > .input-group-prepend > .input-group-text { border-top-right-radius: 0; border-bottom-right-radius: 0; }
.input-group > .input-group-append > .input-group-text { border-top-left-radius: 0; border-bottom-left-radius: 0; }
.btn { display: inline-block; font-weight: 400; text-align: center; vertical-align: middle; user-select: none; border: 1px solid transparent; }
.btn-block { display: block; width: 100%; }
.btn-lg { padding: .5rem 1rem; font-size: 1.25rem; line-height: 1.5; border-radius: .3rem; }
.table { width: 100%; margin-bottom: 1rem; border-collapse: collapse; }
.table td, .table th { padding: .75rem; vertical-align: top; border-top: 1px solid #e8e2f0; }
.table-sm td, .table-sm th { padding: .3rem; }
.table-responsive { display: block; width: 100%; overflow-x: auto; }
.text-right { text-align: right !important; }
.text-muted { color: #6a6673 !important; }
.small { font-size: 80%; }
.font-weight-bold { font-weight: 700 !important; }
.text-uppercase { text-transform: uppercase !important; }
.h6 { font-size: 1rem; }
.mb-0 { margin-bottom: 0 !important; }
.mb-2 { margin-bottom: .5rem !important; }
.mb-3 { margin-bottom: 1rem !important; }
.mb-4 { margin-bottom: 1.5rem !important; }
.mt-2 { margin-top: .5rem !important; }
.mt-3 { margin-top: 1rem !important; }
.mt-4 { margin-top: 1.5rem !important; }
`;

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Paycheck Calculator — Take-Home Pay After Taxes</title>
<meta name="description" content="Free US paycheck calculator. Estimate your take-home pay after federal income tax, FICA, and state income tax. Covers all 50 states and DC. No signup needed." />
<style>
${BOOTSTRAP_SHIM}
${css}
</style>
</head>
<body>
<div class="container" style="max-width: 960px; margin: 0 auto; padding: 24px 15px;">
<main id="paycheck-calculator" class="pc-app" aria-label="Paycheck calculator"></main>
</div>
<script type="module">
${DATA_BLOCK}
${engineSrc}
${uiSrc}
${MOUNT_HELPER}
mountCalculator(document.getElementById("paycheck-calculator"));
</script>
</body>
</html>
`;
writeFileSync(join(DIST, "paycheck-calculator.html"), html);

// ---- 3. WordPress snippets ----
// Server-render the form so the inputs and state list are in the initial HTML
// (crawlable), rather than injected by JS.
const { template } = await import("../src/ui/calculator-ui.js");
const formHtml = template(stateIndex.states);

// Canonical FAQ list. This is the single source of truth for the page body and
// both schema files. It mirrors the FAQ block currently live on the page.
const FAQS = [
  {
    q: "What is the weekly equivalent of an annual salary?",
    a: "Enter your gross annual income, tax year, payment frequency, filing status, and state; then, see the estimated net and itemized deductions. This provides an estimate only, and your employers\u2019 payroll calculation may be different because you might have a different W-4, different benefits, and different taxes that your employer would calculate.",
  },
  {
    q: "There are 52 weeks in a year.",
    a: "Typically pay is weekly, which equals 52 payments per year; biweekly, which equals 26 payments per year; semi-monthly which equals 24 payments per year; and monthly which equals 12 payments per year. Biweekly (twice a week) paydays are every two weeks; semi-monthly (twice a month) paydays are each payday split into two amounts.",
  },
  {
    q: "What is the difference between every other week pay and half-monthly pay?",
    a: "Biweekly pay is payment that is made every other week, which results in 26 payments per year. Semi-monthly pays are paid on a twice monthly basis (24 checks per year). Select the schedule that appears on your pay stub\u2014it\u2019s not changing the amount of money that you are paid, it\u2019s just changing how it is paid out throughout the year.",
  },
  {
    q: "What happens to an hourly paycheck estimate when you work overtime?",
    a: "Choose Hourly and enter the hourly rate and regular hours per week and overtime hours. The calculator assumes that overtime is 1.5 times the number of hours entered. Overtime rules and overtime hours are subject to actual working hours and law \u2013 check with employer.",
  },
  {
    q: "Are 401(k), HSA and health deductions impacting take-home pay?",
    a: "They lower the amount of cash that you receive by the amount deducted but do not have the same tax treatment. The remittance of federal, state and SS/Medicare wages will depend on the remittance and plan. Input the total per pay-period and check it against your payroll and benefits information from your employer.",
  },
  {
    q: "Does the calculator take into account local taxes and paid leaves deductions?",
    a: "No. Local/ city income tax, state disability insurance and paid-family-leave deductions are not included in the estimate. These can impact your paycheck, subject to your work and residing place.",
  },
  {
    q: "Is paycheck withholding the same tax as what I will be paying?",
    a: "No. Paycheck withholding is a portion of your earnings (during the year) deducted from your paycheck to pay your tax obligation. Final tax is calculated at the time of filing based on your total income, deductions, credits and other factors. Use the IRS Withholding Estimator to determine a personal estimate of federal withholding or talk to a tax professional.",
  },
  {
    q: "Why might my actual paycheck be different than the estimate?",
    a: "W-4 elections or information from the payroll system not entered here may be used by your employer. The amount can also be affected by local taxes, state disability or paid-leave programs, benefits costs, timing of the pay period, rounding, and other factors. Compare the itemized estimate with your pay stub and the official state guidance.",
  },
  {
    q: "What tax year is this going to be?",
    a: "Select the year of the paycheck earned \u2013 2025 or 2026. The tax thresholds and withholding guidance may change from year to year, and cannot be substituted for withholding for another year.",
  },
  {
    q: "What is meant by W-4 credits/extra withholding?",
    a: "Open \u201cDeductions & W-4.\u201d Type in the annual amount in Step 3 credits and the extra amount you wish to be taken with each paycheck in Step 4(c). Do not use these fields as substitutes for a W-4 form filed with your employer, but rather use your completed W-4 and existing IRS guidance.",
  },
  {
    q: "Does this calculator cover all states?",
    a: "It provides state options for every 50 state and Washington, DC for tax years 2025 and 2026. State income tax is simplified and the estimate does not include all local taxes and state payroll deduction. For rules specific to your situation, follow the link to your state tax agency.",
  },
];

// The FAQ is defined once and emitted to both the page body and the JSON-LD.
// Google requires FAQPage markup to match content visible on the page, so
// keeping one source prevents the two from drifting apart.
//
// Markup follows the same conventions as the other afreetools calculators
// (see /rule-of-72-calculator): a "rank-math-faq" block with rank-math-question
// / rank-math-answer classes, so the site's existing FAQ styling applies.
const faqHtml = `<h2 class="wp-block-heading" id="faq">FAQ</h2>

<div id="rank-math-faq" class="rank-math-block">
<div class="rank-math-list ">
${FAQS.map(
  (f, i) => `<div id="faq-question-${i + 1}" class="rank-math-list-item">
<h4 class="rank-math-question ">${f.q}</h4>
<div class="rank-math-answer ">

<p>${f.a}</p>

</div>
</div>`
).join("\n")}
</div>
</div>`;

writeFileSync(
  join(WPDIR, "1-paycheck-calculator-page.html"),
  `<!-- Paste into the Page body. Use the Code Editor, not the Visual editor.

  Rank Math SEO fields to set on this Page (these drive the meta description
  and social preview, which are otherwise auto-generated from the form labels):
    Focus keyword : paycheck calculator
    SEO title     : Paycheck Calculator - Estimate Your Take-Home Pay
    Meta description (157 characters):
      Free US paycheck calculator. Estimate your take-home pay after federal
      income tax, FICA, and state income tax. Covers all 50 states and DC. No
      signup needed.

  The paragraph below the heading is not decoration. Search engines and social
  cards read the opening text, and without it the meta description falls back
  to the first form labels ("Tax year 2026 2025 Pay type Salary..."). Keep it.

  The <style> block carries the brand palette and the pieces Bootstrap 4 does
  not provide. The theme already loads Bootstrap 4.6.2, so this is the only
  styling the page needs.
-->
<style>
${css}
</style>

<p class="pc-intro">Estimate your take-home pay per paycheck after federal income tax, FICA (Social Security and Medicare), and state income tax. Choose your pay frequency and filing status, add any 401(k) or HSA contributions, and see your net pay broken down per period. Covers all 50 states and Washington, DC for tax years 2025 and 2026. Everything runs in your browser &mdash; nothing you type is sent anywhere.</p>

<div class="card shadow-sm border-0 mb-5" id="toolCard">
<div class="card-body p-4">

<h2 class="h6 font-weight-bold text-uppercase section-kicker mb-3">Your pay details</h2>

<div id="paycheck-calculator" class="pc-app" aria-label="Paycheck calculator">
${formHtml}
</div>

</div>
</div>

<h2 class="wp-block-heading" id="what-this-calculator-does">What this paycheck calculator does</h2>

<p>This tool turns a gross salary or hourly wage into the amount that actually lands in your bank account. It applies the current federal income tax brackets, the standard deduction for your filing status, Social Security and Medicare (FICA), and a simplified state income tax, then divides the result by your pay frequency.</p>

<p>It handles both salary and hourly pay, including overtime at time and a half. You can also enter pre-tax deductions such as a 401(k), HSA, or health premium, which lower your taxable income before the tax is worked out.</p>

<h2 class="wp-block-heading" id="how-take-home-pay-is-calculated">How your take-home pay is calculated</h2>

<p>The calculation runs in four steps:</p>

<ul class="wp-block-list">
<li><strong>Gross pay.</strong> Your annual salary, or hourly rate times hours worked, converted to the pay period you selected.</li>
<li><strong>Pre-tax deductions.</strong> 401(k), HSA, FSA, and health premiums are subtracted first, so they reduce both income tax and FICA.</li>
<li><strong>Federal tax and FICA.</strong> The standard deduction is applied, the remaining income is run through the marginal brackets, and Social Security (6.2% up to the annual wage base) and Medicare (1.45%) are withheld. Earnings above the additional Medicare threshold are taxed a further 0.9%.</li>
<li><strong>State tax.</strong> A simplified state income tax is applied for your selected state. Nine states do not tax wage income at all: Alaska, Florida, Nevada, New Hampshire, South Dakota, Tennessee, Texas, Washington, and Wyoming.</li>
</ul>

<p>Pay frequency matters more than people expect. A biweekly schedule pays 26 times a year, a semi-monthly schedule 24 times, so the same salary produces different per-paycheck amounts. Choose the frequency that matches your pay stub.</p>

<h2 class="wp-block-heading" id="what-is-not-included">What is not included</h2>

<p>This is an estimate for planning, not a payroll system. It does not include local or city income tax, state disability or paid-family-leave programs, or the specific withholding method your employer uses. It also leaves out any deductions you have not entered. Your actual paycheck can differ by a small amount for these reasons.</p>

${faqHtml}

<h2 class="wp-block-heading" id="related-tools">Related tools</h2>

<ul class="wp-block-list">
<li><a href="/finance/">Money &amp; Pay Calculators</a> &mdash; the rest of the finance hub.</li>
<li><a href="/customer-lifetime-value-calculator">Customer Lifetime Value Calculator</a></li>
<li><a href="/heloc-calculator">HELOC Calculator</a></li>
<li><a href="/era-calculator">ERA Calculator</a></li>
<li><a href="/wacc-calculator">WACC Calculator</a></li>
</ul>

<script type="module">
  import { mountCalculator } from "/wp-content/uploads/tools/paycheck-engine.js";
  mountCalculator(document.getElementById("paycheck-calculator"));
</script>
`
);

writeFileSync(
  join(WPDIR, "2-finance-hub-page.html"),
  `<!-- Paste into the /finance hub Page body. -->
<h2>Money &amp; Pay Calculators</h2>
<p>Free tools for understanding your pay, taxes, and take-home income. No signup, no data leaves your browser.</p>

<ul>
  <li>
    <h3><a href="/finance/paycheck-calculator">Paycheck Calculator</a></h3>
    <p>Estimate your take-home pay per period after federal income tax, FICA, and state income tax.</p>
  </li>
</ul>
`
);

const schemaGraph = [
  {
    "@type": "WebApplication",
    name: "Paycheck Calculator",
    url: "https://afreetools.com/finance/paycheck-calculator",
    applicationCategory: "FinanceApplication",
    operatingSystem: "All",
    browserRequirements: "Requires JavaScript",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    description:
      "Free US paycheck calculator. Estimate take-home pay after federal income tax, Social Security, Medicare, and state income tax.",
  },
  {
    "@type": "FAQPage",
    mainEntity: FAQS.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  },
];

// Rank Math free allows only one schema type per page, so these are written as
// two separate files. It also already emits BreadcrumbList itself, so we do not
// duplicate it here.
const jsonld = (node) =>
  JSON.stringify({ "@context": "https://schema.org", ...node }, null, 2) + "\n";

writeFileSync(join(WPDIR, "3a-schema-webapplication.jsonld"), jsonld(schemaGraph[0]));
writeFileSync(join(WPDIR, "3b-schema-faq.jsonld"), jsonld(schemaGraph[1]));

writeFileSync(
  join(WPDIR, "4-enqueue-snippet.php"),
  `<?php
/**
 * Paycheck calculator: load the engine and add structured data.
 *
 * Two independent jobs in one file. Delete whichever block you don't need.
 *
 * Where to put this, pick ONE:
 *   a) Code Snippets plugin -> Add New -> Run Everywhere
 *      IMPORTANT: paste from the "/**" line below, NOT the "<?php" line.
 *      The plugin adds the opening tag itself; a second one is an error.
 *   b) A small site-specific plugin in wp-content/plugins/
 *   c) A child theme's functions.php  (paste inside the file, no second <?php)
 *
 * Do NOT paste into the parent GeneratePress theme — a theme update erases it.
 */

/**
 * 1. Load the engine without pasting any <script> into the page body.
 *
 * Inline <script type="module"> is the riskiest part of a WordPress install,
 * because the editor can reformat it and break the JS. The engine auto-mounts
 * itself, so enqueueing it alone is enough. Nothing inline, nothing to mangle.
 */
add_action( 'wp_enqueue_scripts', function () {
    // Loads on the calculator page only, so other pages stay unaffected.
    if ( ! is_page( 'paycheck-calculator' ) ) {
        return;
    }

    // Registers and prints as <script type="module" src="...">.
    wp_enqueue_script_module(
        'paycheck-engine',
        content_url( '/uploads/tools/paycheck-engine.js' ),
        array(),
        '1.0.0'   // bump this after re-uploading to bust browser cache
    );
} );

/**
 * 2. Add WebApplication structured data.
 *
 * Use this instead of Rank Math's Custom Schema field, which is a PRO feature.
 * Rank Math free already emits BreadcrumbList, Article, and the FAQPage for the
 * visible FAQ block, so we only add the one type it cannot: WebApplication.
 */
add_action( 'wp_head', function () {
    if ( ! is_page( 'paycheck-calculator' ) ) {
        return;
    }

    $url = 'https://afreetools.com/finance/paycheck-calculator';

    $webapp = array(
        '@context'             => 'https://schema.org',
        '@type'                => 'WebApplication',
        'name'                 => 'Paycheck Calculator',
        'url'                  => $url,
        'applicationCategory'  => 'FinanceApplication',
        'operatingSystem'      => 'All',
        'browserRequirements'  => 'Requires JavaScript',
        'offers'               => array(
            '@type'         => 'Offer',
            'price'         => '0',
            'priceCurrency' => 'USD',
        ),
        'description'          => 'Free US paycheck calculator. Estimate take-home pay after federal income tax, Social Security, Medicare, and state income tax.',
    );

    printf(
        '<script type="application/ld+json">%s</script>' . "\\n",
        wp_json_encode( $webapp, JSON_UNESCAPED_SLASHES )
    );
} );
`
);

const kb = (b) => (Buffer.byteLength(b) / 1024).toFixed(1) + " KB";
console.log("Built:");
console.log(`  dist/paycheck-engine.js          ${kb(engineBundle)}  (external module for WordPress)`);
console.log(`  dist/paycheck-calculator.html    ${kb(html)}  (standalone)`);
console.log(`  dist/wp/1-paycheck-calculator-page.html`);
console.log(`  dist/wp/2-finance-hub-page.html`);
console.log(`  dist/wp/3a-schema-webapplication.jsonld`);
console.log(`  dist/wp/3b-schema-faq.jsonld`);
console.log(`  dist/wp/4-enqueue-snippet.php`);
